### PR TITLE
Eliminate duplicate linting instructions and reorganize for clarity

### PR DESCRIPTION
**Pull request by MOZGIII**

### CODE REVIEW

**Comment by MOZGIII** [comment]
This must be a Travis' internal problem. Please merge this one for me! :smile:

**Comment by parasyte** [comment]
The Travis CI problem is blocking merge. Will have to get this sorted out of band.

**Comment by MOZGIII** [comment]
I can repush this to retrigger the build, maybe that'll help

**Comment by MOZGIII** [comment]
It might be that the branch test is simply not invoked for non-owners. It might be a security policy.

cc @davidnub

**Comment by davidnub** [comment]
Actually it looks related to `clippy` on AMD64

image

**Comment by MOZGIII** [comment]
That's from the successfully completed job, the problem is the one that's stuck:
image

**Comment by davidnub** [comment]
> That's from the successfully completed job, the problem is the one that's stuck:
> image

Yea sorry, you're right. I think perhaps it's related to Travis trying to run on your branch of your repo. I wonder if you set that up to run with the free Travis account if that would solve it?

**Comment by davidnub** [comment]
Or if you add @parasyte or I as maintainers to your repo fork then we can add it to our Travis run.

**Comment by MOZGIII** [comment]
I got my access restored, so I can work around this by recreating the PR from a branch.

> Or if you add @parasyte or I as maintainers to your repo fork then we can add it to our Travis run.

This is a rather odd requirement for a PR. I understand where it comes from, but it seems like it'll create a serious boundary for the open-source community contributors.

In the hindsight, we probably should reconfigure the merge requirement to omit the check for branch tests to pass.

**Comment by davidnub** [comment]
Great that you got your access restored.

> This is a rather odd requirement for a PR. I understand where it comes from, but it seems like it'll create a serious boundary for the open-source community contributors.

I agree that this is odd and shouldn't be necessary. We have a different process in the works when it comes to the internal and external development workflow which will hopefully address some of these challenges going forward.

**Pull request merged**
