### PR TITLE
Upgrade tokio to v1

### PR DESCRIPTION
**Pull request by petrosagg**

### CODE REVIEW

**Comment by petrosagg** [comment]
It looks like the current master is broken as far as CI is concerned so I fixed the warnings in this branch to get the CI to pass

**Comment by petrosagg** [comment]
The only thing that's failing now is beyond my control. It looks like the CI is missing some key? Or it's because the PR is from an external fork. @MOZGIII can you take a look?

**Comment by 650elx** [comment]
@petrosagg Thanks for your contribution.
We are working on updating our RustSDK; I'll close this PR when we release updated version.

**Comment by 650elx** [comment]
@petrosagg We're working on the completly new RustSDK (release date is neither known nor expected to come soon).
I'll try to incorporate your improvements into this repo next week.

**Comment by petrosagg** [comment]
hey @650elx any luck with merging and releasing this PR? We've been using a fork of this in production for a while now with no issues and tests pass in CI

**Comment by petrosagg** [comment]
Just a friendly ping, it would be great to get this PR in

**Review by 650elx — APPROVED** [review]
@petrosagg Thanks for this valuable contribution.
I'll publish newer version of this package asap.

**Comment by petrosagg** [comment]
Awesome! Thank you!

**Pull request merged**
